FROM ubuntu:latest

ARG COMPLIANCE_VERSION=1.3.13
ARG TERRAFORM_VERSION=0.14.3
ARG TERRAGRUNT_VERSION=0.29.2
ARG GO_VERSION=1.16.4
ARG TERRAFORM_DOCS_VERSION=0.13.0

ARG HASHICORP_PGP_KEY
ARG TARGET_ARCH='linux_amd64'

LABEL terraform_compliance.version="${COMPLIANCE_VERSION}"
LABEL terraform.version="${TERRAFORM_VERSION}"
LABEL terragrunt.version="${TERRAGRUNT_VERSION}"

ENV TARGET_ARCH="${TARGET_ARCH}"
ENV HASHICORP_PGP_KEY="${HASHICORP_PGP_KEY}"
ENV GO111MODULE=on
ENV GOPATH=/root/go
ENV TZ=Europe/Dublin
ENV DEBIAN_FRONTEND=noninteractive

RUN  set -ex \
     && BUILD_DEPS='wget unzip gpg curl build-essential' \
     && RUN_DEPS="git tar sudo golang jq python3-pip" \
     && apt-get update \
     && apt-get install -y ${BUILD_DEPS} ${RUN_DEPS} \
     && TERRAFORM_FILE_NAME="terraform_${TERRAFORM_VERSION}_${TARGET_ARCH}.zip" \
     && SHA256SUM_FILE_NAME="terraform_${TERRAFORM_VERSION}_SHA256SUMS" \
     && SHA256SUM_SIG_FILE_NAME="terraform_${TERRAFORM_VERSION}_SHA256SUMS.sig" \
     && SHA256SUM_FILE_NAME_FOR_ARCH="${SHA256SUM_FILE_NAME}.${TARGET_ARCH}" \
     && HASHICORP_PGP_KEY_FILE='hashicorp-pgp-key.pub' \
     && OLD_BASEDIR="$(pwd)" \
     && TMP_DIR=$(mktemp -d) \
     && cd "${TMP_DIR}" \
     && echo "${HASHICORP_PGP_KEY}" > "${HASHICORP_PGP_KEY_FILE}" \
     && wget -q "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/${SHA256SUM_FILE_NAME}" \
     && wget -q "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/${SHA256SUM_SIG_FILE_NAME}" \
     && gpg --import "${HASHICORP_PGP_KEY_FILE}" \
     # && gpg --verify "${SHA256SUM_SIG_FILE_NAME}" "${SHA256SUM_FILE_NAME}" \
     && wget -q "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/${TERRAFORM_FILE_NAME}" \
     && grep "${TERRAFORM_FILE_NAME}" "${SHA256SUM_FILE_NAME}" > "${SHA256SUM_FILE_NAME_FOR_ARCH}" \
     && wget --quiet "https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64" \
     && chmod +x terragrunt_linux_amd64 \
     && mv terragrunt_linux_amd64 /usr/local/bin/terragrunt \
     && ls -al . \
     && sha256sum -c "${SHA256SUM_FILE_NAME_FOR_ARCH}" \
     && unzip "${TERRAFORM_FILE_NAME}" \
     && install terraform /usr/bin/ \
     && wget --quiet "https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz" \
     && tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz \
     && /usr/local/go/bin/go get "github.com/terraform-docs/terraform-docs@v${TERRAFORM_DOCS_VERSION}" \
     && /usr/local/go/bin/go get  "golang.org/x/lint/golint" \
     && curl https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash \
     && cd "${OLD_BASEDIR}" \
     && unset OLD_BASEDIR \
     && rm -vrf ${TMP_DIR} \
     && pip install --upgrade pip \
     && pip install terraform-compliance=="${COMPLIANCE_VERSION}" \
     && pip install pre-commit   \
     && pip install awscli \
     && apt-get remove -y ${BUILD_DEPS} \
     && apt-get autoremove -y \
     && apt-get clean -y \
     && rm -rf /var/lib/apt/lists/* \
     && mkdir -p /target

RUN echo "Host *" >> /etc/ssh/ssh_config
RUN echo " StrictHostKeyChecking no" >> /etc/ssh/ssh_config

WORKDIR /target
ENTRYPOINT ["/bin/bash"]
